version: '3.8'
services:
 dynamodb:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal
 
 lambda:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/task/src
      - ~/.aws:/root/.aws
    ports:
      - "3001:3001"